services:
  - type: web
    name: sample-ruby-app-1
    env: ruby
    envVars:
      - key: DEFAULT_RUBY_VERSION
        value: 3.1
    buildCommand: cd ruby-app-1 && ./render-build.sh
    startCommand: cd ruby-app-1 &&./render-start.sh
  - type: web
    name: sample-ruby-app-2
    env: ruby
    envVars:
      - key: DEFAULT_RUBY_VERSION
        value: 2.7
    buildCommand: ./render-build.sh
    startCommand: ./render-start.sh
