services:
  - type: web
    name: sample-ruby-app-1
    env: ruby
    buildCommand: cd ruby-app-1 && ./render-build.sh
    startCommand: cd ruby-app-1 &&./render-start.sh
  - type: web
    name: sample-ruby-app-2
    env: ruby
    buildCommand: cd ruby-app-2 && ./render-build.sh
    startCommand: cd ruby-app-2 &&./render-start.sh
